name: NUGET-PACK-PUSH

on:
  release:
    types:
      - published
      - edited

env:
  VERSION: 0.0.0
  BRANCH: ''  
  
jobs:  
  build:
    name: Build and verify library    
    runs-on: ubuntu-latest  
    steps:
      - name: Getting branch name and release version
        run: |          
          echo "::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/} | sed 's/\//_/g')"
          echo "::set-env name=VERSION::${GITHUB_REF/refs\/tags\/v/}"      
      - run: echo Version $VERSION - Branch $BRANCH - Commit $COMMIT
      - uses: actions/checkout@v1   
      - name: Update tokens in project files
        uses: cschleiden/replace-tokens@v1
        with:
          files: '["*.csproj", "**/*.csproj"]'
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.202'
      - name: Building library
        run: |
          dotnet restore src
          dotnet build src/bunit.core/ -c Release --no-restore -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
          dotnet build src/bunit.web/ -c Release --no-restore -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
          dotnet build src/bunit.xunit/ -c Release --no-restore -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
          dotnet build src/bunit.testassets/ -c Release --no-restore
      - name: Running unit tests
        run: |
          dotnet test src/bunit.core.tests/ -c Release --no-restore --verbosity normal /nowarn:CS1591
          dotnet test src/bunit.web.tests/ -c Release --no-restore --verbosity normal /nowarn:CS1591
          dotnet test src/bunit.xunit.tests/ -c Release --no-restore --verbosity normal /nowarn:CS1591
      - name: Creating library package
        run: |
          dotnet pack src/bunit.core/ -c Release -o ${GITHUB_WORKSPACE}/lib -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
          dotnet pack src/bunit.web/ -c Release -o ${GITHUB_WORKSPACE}/lib -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
          dotnet pack src/bunit.xunit/ -c Release -o ${GITHUB_WORKSPACE}/lib -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
          dotnet pack src/bunit/ -c Release -o ${GITHUB_WORKSPACE}/lib -p:version=$VERSION -p:RepositoryBranch=$BRANCH -p:ContinuousIntegrationBuild=true -p:DeterministicSourcePaths=true
      - name: Buidling template package
        run: dotnet pack templates/bunit-project/ -c Release -o ${GITHUB_WORKSPACE}/templates -p:version=$VERSION
      - name: Verifying template
        run: |
          dotnet new --install ${GITHUB_WORKSPACE}/templates/bunit.template.$VERSION.nupkg
          dotnet new bunit --no-restore -o ${GITHUB_WORKSPACE}/Test
          dotnet restore ${GITHUB_WORKSPACE}/Test/Test.csproj --source ${GITHUB_WORKSPACE}/lib
          dotnet test ${GITHUB_WORKSPACE}/Test
      - name: Push packages to NuGet.org
        run: | 
          dotnet nuget push ${GITHUB_WORKSPACE}/lib/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          dotnet nuget push ${GITHUB_WORKSPACE}/template/*.nupkg -k ${{ secrets.NUGET_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate       
