name: verification-dotnet-nightly

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  verify-bunit:
    name: ðŸ‘Œ Verify bUnit
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/nightly/sdk:7.0

    steps:
      - name: ðŸŒ› Show dotnet version
        run: |
          dotnet --info

      - name: ðŸ›’ Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ðŸ“¦ Setup nuget nightly builds
        run: |
          dotnet restore --verbosity normal -s https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json -s https://api.nuget.org/v3/index.json

      - name: ðŸ§ª Run unit tests
        run: |
          dotnet test ./tests/bunit.core.tests/bunit.core.tests.csproj -c release --no-restore -f net7.0 --logger:"console;verbosity=normal" --blame-hang --blame-hang-timeout 1m --blame-hang-dump-type none
          dotnet test ./tests/bunit.web.tests/bunit.web.tests.csproj -c release --no-restore -f net7.0 --logger:"console;verbosity=normal" --blame-hang --blame-hang-timeout 1m --blame-hang-dump-type none
          dotnet test ./tests/bunit.web.testcomponents.tests/bunit.web.testcomponents.tests.csproj -c release --no-restore -f net7.0 --logger:"console;verbosity=normal" --blame-hang --blame-hang-timeout 1m --blame-hang-dump-type none

      - name: ðŸ§¾ Collect dotnet information
        if: failure()
        run: |
          echo "DOTNET_VERSION=$(dotnet --version)" >> $GITHUB_ENV
          echo $DOTNET_VERSION

      - name: âš¡ Create issue if failed
        if: failure()
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADJECTIVE: DOTNET_VERSION
        with:
          filename: .github/nightly-failed.md
          update_existing: true
